services:
  web:
    image: nginx:latest
    container_name: nginx-web
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
      - ./logs:/var/log/nginx
    restart: unless-stopped
  mysql:
    image: mysql:8.0
    container_name: custom-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root              # Thêm dòng này
      PMA_PASSWORD: root          # Thêm dòng này
      UPLOAD_LIMIT: 64M
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:80"
    restart: unless-stopped
  nodejs:
    build: './nodejs'
    container_name: nodejs
    ports:
      - "3000:3000"
